User.create!([
  {email: "alice@test.com", username: "ありす", password: "pokemon", password_confirmation: "pokemon"}
])
Battle.create!([
  {my_rate: 1500, opp_rate: 1475, result: false, user_id: 1},
  {my_rate: 1483, opp_rate: 1498, result: true, user_id: 1},
  {my_rate: 1499, opp_rate: 1514, result: false, user_id: 1},
  {my_rate: 1484, opp_rate: 1374, result: false, user_id: 1},
  {my_rate: 1463, opp_rate: 1419, result: true, user_id: 1},
  {my_rate: 1478, opp_rate: 1483, result: true, user_id: 1},
  {my_rate: 1494, opp_rate: 1461, result: false, user_id: 1},
  {my_rate: 1477, opp_rate: 1484, result: true, user_id: 1},
  {my_rate: 1493, opp_rate: 1446, result: false, user_id: 1},
  {my_rate: 1475, opp_rate: 1556, result: true, user_id: 1},
  {my_rate: 1494, opp_rate: 1449, result: true, user_id: 1}
])
MyPoke.create!([
  {name: "メガボーマンダ", item: "メガストーン", ability: "スカイスキン", in_party: true, user_id: 1},
  {name: "ゲッコウガ", item: "おうじゃのしるし", ability: "へんげんじざい", in_party: true, user_id: 1},
  {name: "カプ・コケコ", item: "シュカのみ", ability: "エレキメイカー", in_party: true, user_id: 1},
  {name: "ワルビアル", item: "こだわりスカーフ", ability: "いかく", in_party: true, user_id: 1},
  {name: "ナットレイ", item: "たべのこし", ability: "てつのトゲ", in_party: true, user_id: 1},
  {name: "ペンドラー", item: "ドクZ", ability: "かそく", in_party: true, user_id: 1}
])
OppPoke.create!([
  {name: "テッカグヤ", item: "たべのこし", ability: ""},
  {name: "グライオン", item: "どくどくだま", ability: "ポイズンヒール"},
  {name: "メガヘラクロス", item: "メガストーン", ability: ""},
  {name: "クレセリア", item: "ゴツゴツメット", ability: ""},
  {name: "ヒードラン", item: "たべのこし", ability: ""},
  {name: "メガゲンガー", item: "メガストーン", ability: ""},
  {name: "グライオン", item: "どくどくだま", ability: "ポイズンヒール"},
  {name: "エアームド", item: "ゴツゴツメット", ability: ""},
  {name: "メガリザードンY", item: "メガストーン", ability: "ひでり"},
  {name: "カプ・レヒレ", item: "", ability: "ミストメイカー"},
  {name: "ガブリアス", item: "", ability: "さめはだ"},
  {name: "サザンドラ", item: "", ability: ""},
  {name: "ダダリン", item: "たべのこし", ability: ""},
  {name: "カプ・コケコ", item: "", ability: ""},
  {name: "ガブリアス", item: "", ability: ""},
  {name: "パルシェン", item: "きあいのタスキ", ability: ""},
  {name: "メガリザードンX", item: "メガストーン", ability: ""},
  {name: "ギギギアル", item: "", ability: ""},
  {name: "メガフシギバナ", item: "メガストーン", ability: ""},
  {name: "ギャラドス", item: "", ability: ""},
  {name: "エアームド", item: "", ability: ""},
  {name: "ガブリアス", item: "いのちのたま", ability: ""},
  {name: "フラージェス", item: "たべのこし", ability: ""},
  {name: "ハピナス", item: "", ability: ""},
  {name: "カビゴン", item: "", ability: "めんえき"},
  {name: "サンダー", item: "", ability: ""},
  {name: "カビゴン", item: "オボンのみ", ability: ""},
  {name: "メガリザードンX", item: "メガストーン", ability: ""},
  {name: "カバルドン", item: "さらさらいわ", ability: ""},
  {name: "カプ・テテフ", item: "こだわりスカーフ", ability: ""},
  {name: "キノガッサ", item: "", ability: ""}
])
BattleMyPoke.create!([
  {battle_id: 1, my_poke_id: 6, comment: nil},
  {battle_id: 1, my_poke_id: 5, comment: nil},
  {battle_id: 1, my_poke_id: 1, comment: nil},
  {battle_id: 2, my_poke_id: 2, comment: "いざとなったらいわなだれでゴリ押せて強い ヒードランはそれで突破した"},
  {battle_id: 2, my_poke_id: 4, comment: "結局あまり刺さってなかった 裏のコケコ意識の採用だったからいいけど"},
  {battle_id: 2, my_poke_id: 5, comment: "メガヘラのインファで落ちてあっそっかぁ……って なった"},
  {battle_id: 3, my_poke_id: 3, comment: "メガゲンが突っ張ってくるのを読めずに死亡 良くない"},
  {battle_id: 3, my_poke_id: 4, comment: "メガゲンに対しては強気で出すべきだった スカーフだし"},
  {battle_id: 3, my_poke_id: 5, comment: "結果的にイマイチ刺さってませんでしたね……選出力よ"},
  {battle_id: 4, my_poke_id: 2, comment: "メガリザ落とせたのはいいんだけど……冷B入れても良いかも？"},
  {battle_id: 4, my_poke_id: 1, comment: "臆病だと無振りレヒレ半分も削れなくてワロタ"},
  {battle_id: 4, my_poke_id: 3, comment: "ガブリアスの地震読みでマンダ出すべきだったしこれが敗因 無傷からなら勝てる"},
  {battle_id: 5, my_poke_id: 6, comment: "やっぱ守るあった方がつええわ"},
  {battle_id: 5, my_poke_id: 3, comment: "出番ありませんでしたね……"},
  {battle_id: 5, my_poke_id: 2, comment: "一応耐えれて上から殴れる相手に受け出しは効くっぽい"},
  {battle_id: 6, my_poke_id: 6, comment: "加速つええ"},
  {battle_id: 6, my_poke_id: 1, comment: "仕事はしたかな"},
  {battle_id: 6, my_poke_id: 3, comment: "シュカコケコ，シュカで地震受ける前に何かしらダメージ食らってるからしんどい"},
  {battle_id: 7, my_poke_id: 6, comment: "流石にメガバナには勝てなかった"},
  {battle_id: 7, my_poke_id: 1, comment: "ギャラで消費しなければメガバナ落とせたな……"},
  {battle_id: 7, my_poke_id: 5, comment: "HBギャラごときに出さないのが失敗だった"},
  {battle_id: 8, my_poke_id: 3, comment: "先発コケコいい感じ"},
  {battle_id: 8, my_poke_id: 5, comment: "珠ガブの剣舞地震は流石に痛かった 耐えたけど"},
  {battle_id: 8, my_poke_id: 1, comment: "地震読みで出していい具合に勝てましたね"},
  {battle_id: 9, my_poke_id: 6, comment: "普通にハピナスメガホーンで落とせるしつらい"},
  {battle_id: 9, my_poke_id: 5, comment: "完全に対策されてた"},
  {battle_id: 9, my_poke_id: 2, comment: "コイツ出した理由がよく分からなかったな"},
  {battle_id: 10, my_poke_id: 3, comment: "サンダーは等倍の10万の方が効きそう エレキフィールドは下手な二倍より火力出ます"},
  {battle_id: 10, my_poke_id: 4, comment: "舞ったメガリザXをほとんど損失なく落とせるのは強い ガブと違ってドラゴン技で落とされることもないし"},
  {battle_id: 10, my_poke_id: 5, comment: "控えの誰か意識で出したんだろうという気はする"},
  {battle_id: 11, my_poke_id: 2, comment: "カバルドンの地震をすかしたり面白い動きは出来た"},
  {battle_id: 11, my_poke_id: 4, comment: "出番無しで終わりましたね"},
  {battle_id: 11, my_poke_id: 5, comment: "めざ炎のないテテフなら問題なく対処できそう"}
])
BattleOppPoke.create!([
  {battle_id: 1, opp_poke_id: 1, comment: nil},
  {battle_id: 1, opp_poke_id: 2, comment: nil},
  {battle_id: 2, opp_poke_id: 3, comment: "インファは強いけど中速だしゲッコウガがよく刺さってた"},
  {battle_id: 2, opp_poke_id: 4, comment: "ゴツメダメがちょっときになるけど，これもゲッコウガで対処できた"},
  {battle_id: 2, opp_poke_id: 5, comment: "いわなだれで突破されてたのかわいそうだった といっても削れてたからひるみ1回だけだけど"},
  {battle_id: 3, opp_poke_id: 6, comment: "ワルビアルのカモだけど変な読みしてコケコを落とされた"},
  {battle_id: 3, opp_poke_id: 7, comment: "もうこいつめんどいわー 対策でコケコ入れたけど対策になってるのか分からなかったし"},
  {battle_id: 3, opp_poke_id: 8, comment: "こいつもめんどいわー マンダで焼き殺したかった"},
  {battle_id: 4, opp_poke_id: 9, comment: "ゲッコウガ先輩の前には為す術もありませんでしたね 読まれたらしんどかった気がする"},
  {battle_id: 4, opp_poke_id: 10, comment: "普通にペンちゃんとかいたのに出さなかったのマジで敗因"},
  {battle_id: 4, opp_poke_id: 11, comment: "地震読み交代くらいすべきだった"},
  {battle_id: 5, opp_poke_id: 12, comment: "初手守ったから持ち物わかんなかったな"},
  {battle_id: 5, opp_poke_id: 13, comment: "コイツ意外と硬い"},
  {battle_id: 5, opp_poke_id: 14, comment: "加速したペンちゃんの前には為す術もありませんわ"},
  {battle_id: 6, opp_poke_id: 15, comment: "初手ガブの可能性は考慮しつつ動くべきかもしれない"},
  {battle_id: 6, opp_poke_id: 16, comment: "S70なので上から殴れるなら普通に1対1交換できる"},
  {battle_id: 6, opp_poke_id: 17, comment: "最後竜舞せずにそのまま地震とかフレドラとか打たれてたら負けてたと思う"},
  {battle_id: 7, opp_poke_id: 18, comment: "何したいのかよく分からなかった"},
  {battle_id: 7, opp_poke_id: 19, comment: "注意をもっと向けるべきだった"},
  {battle_id: 7, opp_poke_id: 20, comment: "思ったより攻撃力なかった この知識の差で負けたな"},
  {battle_id: 8, opp_poke_id: 21, comment: "ボルチェンでまさか落ちるとは"},
  {battle_id: 8, opp_poke_id: 22, comment: "相手がガブ捨てなければワンチャンやられてた？それはないか"},
  {battle_id: 8, opp_poke_id: 23, comment: "こいつの舐めプねがいごとが勝因と言えなくもない"},
  {battle_id: 9, opp_poke_id: 24, comment: "物理方面思ったより低い"},
  {battle_id: 9, opp_poke_id: 25, comment: "めんえきだし硬いしあくび打ってくるしつらかった 格闘技欲しいかもしれない"},
  {battle_id: 10, opp_poke_id: 26, comment: "コケコとの殴り合いはあまり意味がなくて結局ワルビアル先輩で落とした感"},
  {battle_id: 10, opp_poke_id: 27, comment: "鈍いめっちゃ積んできたけどナットレイ見たらすぐに引いた"},
  {battle_id: 10, opp_poke_id: 28, comment: "舞うとコケコは抜いてきたがワルビアルは抜けなかった"},
  {battle_id: 11, opp_poke_id: 29, comment: "あくびステロが面倒 怠けるを持ってたらもっと面倒だった"},
  {battle_id: 11, opp_poke_id: 30, comment: "後ろがキノガッサだったから引けなかったんだろう 低レートなのであまり参考にならない"},
  {battle_id: 11, opp_poke_id: 31, comment: "ゲッコウガでもナットレイでも倒せそう ナットレイにはマッパもタネマシンガンもあまり効かないのでは"}
])
Eval.create!([
  {eval: -3, battle_id: 1, my_poke_id: 6, opp_poke_id: 1},
  {eval: -3, battle_id: 1, my_poke_id: 6, opp_poke_id: 2},
  {eval: -2, battle_id: 1, my_poke_id: 5, opp_poke_id: 1},
  {eval: -3, battle_id: 1, my_poke_id: 5, opp_poke_id: 2},
  {eval: 2, battle_id: 1, my_poke_id: 1, opp_poke_id: 1},
  {eval: -3, battle_id: 1, my_poke_id: 1, opp_poke_id: 2},
  {eval: 3, battle_id: 2, my_poke_id: 2, opp_poke_id: 3},
  {eval: 1, battle_id: 2, my_poke_id: 2, opp_poke_id: 4},
  {eval: 1, battle_id: 2, my_poke_id: 2, opp_poke_id: 5},
  {eval: -2, battle_id: 2, my_poke_id: 4, opp_poke_id: 3},
  {eval: 0, battle_id: 2, my_poke_id: 4, opp_poke_id: 4},
  {eval: 3, battle_id: 2, my_poke_id: 4, opp_poke_id: 5},
  {eval: -2, battle_id: 2, my_poke_id: 5, opp_poke_id: 3},
  {eval: 2, battle_id: 2, my_poke_id: 5, opp_poke_id: 4},
  {eval: -1, battle_id: 2, my_poke_id: 5, opp_poke_id: 5},
  {eval: -3, battle_id: 3, my_poke_id: 3, opp_poke_id: 6},
  {eval: 2, battle_id: 3, my_poke_id: 3, opp_poke_id: 7},
  {eval: 2, battle_id: 3, my_poke_id: 3, opp_poke_id: 8},
  {eval: 2, battle_id: 3, my_poke_id: 4, opp_poke_id: 6},
  {eval: 0, battle_id: 3, my_poke_id: 4, opp_poke_id: 7},
  {eval: -2, battle_id: 3, my_poke_id: 4, opp_poke_id: 8},
  {eval: 1, battle_id: 3, my_poke_id: 5, opp_poke_id: 6},
  {eval: -1, battle_id: 3, my_poke_id: 5, opp_poke_id: 7},
  {eval: -1, battle_id: 3, my_poke_id: 5, opp_poke_id: 8},
  {eval: 3, battle_id: 4, my_poke_id: 2, opp_poke_id: 9},
  {eval: -2, battle_id: 4, my_poke_id: 2, opp_poke_id: 10},
  {eval: 0, battle_id: 4, my_poke_id: 2, opp_poke_id: 11},
  {eval: 0, battle_id: 4, my_poke_id: 1, opp_poke_id: 9},
  {eval: -3, battle_id: 4, my_poke_id: 1, opp_poke_id: 10},
  {eval: 2, battle_id: 4, my_poke_id: 1, opp_poke_id: 11},
  {eval: 3, battle_id: 4, my_poke_id: 3, opp_poke_id: 9},
  {eval: -2, battle_id: 4, my_poke_id: 3, opp_poke_id: 10},
  {eval: 1, battle_id: 4, my_poke_id: 3, opp_poke_id: 11},
  {eval: 3, battle_id: 5, my_poke_id: 6, opp_poke_id: 12},
  {eval: -2, battle_id: 5, my_poke_id: 6, opp_poke_id: 13},
  {eval: 3, battle_id: 5, my_poke_id: 6, opp_poke_id: 14},
  {eval: 0, battle_id: 5, my_poke_id: 3, opp_poke_id: 12},
  {eval: 0, battle_id: 5, my_poke_id: 3, opp_poke_id: 13},
  {eval: 0, battle_id: 5, my_poke_id: 3, opp_poke_id: 14},
  {eval: 2, battle_id: 5, my_poke_id: 2, opp_poke_id: 12},
  {eval: 3, battle_id: 5, my_poke_id: 2, opp_poke_id: 13},
  {eval: -3, battle_id: 5, my_poke_id: 2, opp_poke_id: 14},
  {eval: -1, battle_id: 6, my_poke_id: 6, opp_poke_id: 15},
  {eval: -1, battle_id: 6, my_poke_id: 6, opp_poke_id: 16},
  {eval: -1, battle_id: 6, my_poke_id: 6, opp_poke_id: 17},
  {eval: 2, battle_id: 6, my_poke_id: 1, opp_poke_id: 15},
  {eval: -1, battle_id: 6, my_poke_id: 1, opp_poke_id: 16},
  {eval: 2, battle_id: 6, my_poke_id: 1, opp_poke_id: 17},
  {eval: 0, battle_id: 6, my_poke_id: 3, opp_poke_id: 15},
  {eval: 0, battle_id: 6, my_poke_id: 3, opp_poke_id: 16},
  {eval: 0, battle_id: 6, my_poke_id: 3, opp_poke_id: 17},
  {eval: 3, battle_id: 7, my_poke_id: 6, opp_poke_id: 18},
  {eval: -2, battle_id: 7, my_poke_id: 6, opp_poke_id: 19},
  {eval: -2, battle_id: 7, my_poke_id: 6, opp_poke_id: 20},
  {eval: 2, battle_id: 7, my_poke_id: 1, opp_poke_id: 18},
  {eval: 2, battle_id: 7, my_poke_id: 1, opp_poke_id: 19},
  {eval: -1, battle_id: 7, my_poke_id: 1, opp_poke_id: 20},
  {eval: 0, battle_id: 7, my_poke_id: 5, opp_poke_id: 18},
  {eval: -2, battle_id: 7, my_poke_id: 5, opp_poke_id: 19},
  {eval: 3, battle_id: 7, my_poke_id: 5, opp_poke_id: 20},
  {eval: 3, battle_id: 8, my_poke_id: 3, opp_poke_id: 21},
  {eval: 0, battle_id: 8, my_poke_id: 3, opp_poke_id: 22},
  {eval: 2, battle_id: 8, my_poke_id: 3, opp_poke_id: 23},
  {eval: -2, battle_id: 8, my_poke_id: 5, opp_poke_id: 21},
  {eval: -2, battle_id: 8, my_poke_id: 5, opp_poke_id: 22},
  {eval: 3, battle_id: 8, my_poke_id: 5, opp_poke_id: 23},
  {eval: 3, battle_id: 8, my_poke_id: 1, opp_poke_id: 21},
  {eval: 2, battle_id: 8, my_poke_id: 1, opp_poke_id: 22},
  {eval: -1, battle_id: 8, my_poke_id: 1, opp_poke_id: 23},
  {eval: 0, battle_id: 9, my_poke_id: 6, opp_poke_id: 24},
  {eval: 0, battle_id: 9, my_poke_id: 6, opp_poke_id: 25},
  {eval: 0, battle_id: 9, my_poke_id: 5, opp_poke_id: 24},
  {eval: 0, battle_id: 9, my_poke_id: 5, opp_poke_id: 25},
  {eval: 0, battle_id: 9, my_poke_id: 2, opp_poke_id: 24},
  {eval: 0, battle_id: 9, my_poke_id: 2, opp_poke_id: 25},
  {eval: -1, battle_id: 10, my_poke_id: 3, opp_poke_id: 26},
  {eval: 0, battle_id: 10, my_poke_id: 3, opp_poke_id: 27},
  {eval: -2, battle_id: 10, my_poke_id: 3, opp_poke_id: 28},
  {eval: 3, battle_id: 10, my_poke_id: 4, opp_poke_id: 26},
  {eval: 2, battle_id: 10, my_poke_id: 4, opp_poke_id: 27},
  {eval: 2, battle_id: 10, my_poke_id: 4, opp_poke_id: 28},
  {eval: -2, battle_id: 10, my_poke_id: 5, opp_poke_id: 26},
  {eval: 2, battle_id: 10, my_poke_id: 5, opp_poke_id: 27},
  {eval: -3, battle_id: 10, my_poke_id: 5, opp_poke_id: 28},
  {eval: 2, battle_id: 11, my_poke_id: 2, opp_poke_id: 29},
  {eval: -3, battle_id: 11, my_poke_id: 2, opp_poke_id: 30},
  {eval: 3, battle_id: 11, my_poke_id: 2, opp_poke_id: 31},
  {eval: 0, battle_id: 11, my_poke_id: 4, opp_poke_id: 29},
  {eval: -3, battle_id: 11, my_poke_id: 4, opp_poke_id: 30},
  {eval: -2, battle_id: 11, my_poke_id: 4, opp_poke_id: 31},
  {eval: 2, battle_id: 11, my_poke_id: 5, opp_poke_id: 29},
  {eval: 3, battle_id: 11, my_poke_id: 5, opp_poke_id: 30},
  {eval: 3, battle_id: 11, my_poke_id: 5, opp_poke_id: 31}
])
